set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-syntastic/syntastic'

call vundle#end()

filetype plugin indent on

let g:syntastic_cpp_compiler_options = '-std=c++17 -Wall -Werror -Wpedantic'
let g:syntastic_cpp_check_header = 1

" Jump to last position when opening a file
if has("autocmd")
	au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
	   \| exe "normal! g'\"" | endif
endif
