set nocompatible
set visualbell
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
set path+=**

set expandtab

set wildmenu

" Load Plugins
call vundle#begin()

"plugins
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'rust-lang/rust.vim'
Plugin 'raku/vim-raku'

" colorschemes
Plugin 'tomasr/molokai'

call vundle#end()

filetype plugin indent on
set formatoptions+=cro
colorscheme molokai

let g:syntastic_cpp_compiler_options = '-std=c++2a -Wall -Werror -Wpedantic'
let g:syntastic_cpp_check_header = 1

" Jump to last known position when opening a file
if has("autocmd")
	au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
	   \| exe "normal! g'\"" | endif
endif
