# vi:syntax=bash
# If not running interactively, don't do anything

case $- in
    *i*) ;;
      *) return;;
esac

for file in $HOME/.bash/*; do source $file; done

# Setup Colors and PS1
eval "$(dircolors -b)"
GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
PS1="$Green$UserName@$HostName:$Blue$Directory$EndColour\$ "
source "$HOME/.cargo/env"
