alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias lla='ls -la'
alias l='ls -CF'
alias sl='ls'

alias atp='apt'
alias apt='sudo apt'

alias nix-shell='nix-shell --pure -p'

# force bash to check the sudo command for aliases
alias sudo='sudo '
